use_frameworks!

platform :ios, '9.0'

target 'gitlibtest_Example' do
  pod 'gitlibtest', :path => '../'

  target 'gitlibtest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
